name: "ecmus-scheduler"
namespace: "ecmus"
resource_count: 2
connector: "kubernetes"
connector_config: "./connector_config.yaml"
maximum_migrations: 3
maximum_cloud_offload: 5
flush_period_duration: 1000  # ms
cloud_suggest_duration: 5000  # ms
health_check_duration: 3000  # ms
recover_retry_duration: 5000  # ms
batch_size: 10
