name: ecmus
namespace: ecmus
resource_count: 2
batch_size: 10
maximum_migrations: 3
maximum_cloud_offload: 5
connector: kubernetes
connector_config: ./config
flush_period_duration: 1000
cloud_suggest_duration: 1000
health_check_duration: 10000
recover_retry_duration: 5000
